# Generated by Django 5.1.7 on 2025-04-18 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_term_score_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.term'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
